# MySQL.  Versions 4.1 and 5.0 are recommended.

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qwikist_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qwikist_test
  pool: 5
  username: root
  password:
  host: localhost
